receivers:
    otlp:
        protocols:
            grpc: null
            http: null
processors:
    batch:
        timeout: 100ms
exporters:
    otlp/1:
        endpoint: tracetest:4317
        tls:
            insecure: true
service:
    pipelines:
        traces/1:
            receivers:
                - otlp
            processors:
                - batch
            exporters:
                - otlp/1
