services:
    cache:
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            timeout: 3s
            interval: 1s
            retries: 60
        image: redis:6
        networks:
            default: null
        restart: unless-stopped
    demo-api:
        depends_on:
            cache:
                condition: service_healthy
            postgres:
                condition: service_healthy
            queue:
                condition: service_healthy
        environment:
            COLLECTOR_ENDPOINT: http://otel-collector:4317
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
            NPM_RUN_COMMAND: api
            POKE_API_BASE_URL: https://pokeapi.co/api/v2
            RABBITMQ_HOST: queue
            REDIS_URL: cache
        healthcheck:
            test:
                - CMD
                - wget
                - --spider
                - localhost:8081
            timeout: 3s
            interval: 1s
            retries: 60
        image: kubeshop/demo-pokemon-api:latest
        networks:
            default: null
        ports:
            - mode: ingress
              target: 8081
              published: 8081
              protocol: tcp
        pull_policy: always
        restart: unless-stopped
    demo-rpc:
        depends_on:
            cache:
                condition: service_healthy
            postgres:
                condition: service_healthy
            queue:
                condition: service_healthy
        environment:
            COLLECTOR_ENDPOINT: http://otel-collector:4317
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
            NPM_RUN_COMMAND: rpc
            POKE_API_BASE_URL: https://pokeapi.co/api/v2
            RABBITMQ_HOST: queue
            REDIS_URL: cache
        healthcheck:
            test:
                - CMD
                - lsof
                - -i
                - "8082"
            timeout: 3s
            interval: 1s
            retries: 60
        image: kubeshop/demo-pokemon-api:latest
        networks:
            default: null
        ports:
            - mode: ingress
              target: 8082
              published: 8082
              protocol: tcp
        pull_policy: always
        restart: unless-stopped
    demo-worker:
        depends_on:
            cache:
                condition: service_healthy
            postgres:
                condition: service_healthy
            queue:
                condition: service_healthy
        environment:
            COLLECTOR_ENDPOINT: http://otel-collector:4317
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
            NPM_RUN_COMMAND: worker
            POKE_API_BASE_URL: https://pokeapi.co/api/v2
            RABBITMQ_HOST: queue
            REDIS_URL: cache
        image: kubeshop/demo-pokemon-api:latest
        networks:
            default: null
        pull_policy: always
        restart: unless-stopped
    otel-collector:
        command:
            - --config
            - /otel-local-config.yaml
        environment:
            TRACETEST_ENDPOINT: tracetest:4317
        image: otel/opentelemetry-collector-contrib:0.59.0
        networks:
            default: null
        volumes:
            - type: bind
              source: ./collector.config.yaml
              target: /otel-local-config.yaml
              bind:
                create_host_path: true
    postgres:
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
            timeout: 5s
            interval: 1s
            retries: 60
        image: postgres:14
        networks:
            default: null
    queue:
        healthcheck:
            test:
                - CMD-SHELL
                - rabbitmq-diagnostics -q check_running
            timeout: 5s
            interval: 1s
            retries: 60
        image: rabbitmq:3.8-management
        networks:
            default: null
        restart: unless-stopped
    tracetest:
        command:
            - --provisioning-file
            - /app/provision.yaml
        depends_on:
            otel-collector:
                condition: service_started
            postgres:
                condition: service_healthy
        environment:
            TRACETEST_DEV: ${TRACETEST_DEV}
        extra_hosts:
            host.docker.internal: host-gateway
        healthcheck:
            test:
                - CMD
                - wget
                - --spider
                - localhost:11633
            timeout: 3s
            interval: 1s
            retries: 60
        image: kubeshop/tracetest:v0.11.8
        networks:
            default: null
        ports:
            - mode: ingress
              target: 11633
              published: 11633
              protocol: tcp
        volumes:
            - type: bind
              source: tracetest.yaml
              target: /app/tracetest.yaml
            - type: bind
              source: ./tracetest-provision.yaml
              target: /app/provision.yaml
networks:
    default:
        name: _default
