services:
    otel-collector:
        command:
            - --config
            - /otel-local-config.yaml
        environment:
            TRACETEST_ENDPOINT: tracetest:4317
        image: otel/opentelemetry-collector-contrib:0.59.0
        networks:
            default: null
        ports:
            - mode: ingress
              target: 4318
              published: 4318
              protocol: tcp
        volumes:
            - type: bind
              source: ./collector.config.yaml
              target: /otel-local-config.yaml
              bind:
                create_host_path: true
    postgres:
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
            timeout: 5s
            interval: 1s
            retries: 60
        image: postgres:14
        networks:
            default: null
        ports:
            - mode: ingress
              target: 5432
              published: 5432
              protocol: tcp
    tracetest:
        command:
            - --provisioning-file
            - /app/provision.yaml
        depends_on:
            otel-collector:
                condition: service_started
            postgres:
                condition: service_healthy
        environment:
            TRACETEST_DEV: ${TRACETEST_DEV}
        extra_hosts:
            host.docker.internal: host-gateway
        healthcheck:
            test:
                - CMD
                - wget
                - --spider
                - localhost:11633
            timeout: 3s
            interval: 1s
            retries: 60
        image: kubeshop/tracetest:v0.11.8
        networks:
            default: null
        ports:
            - mode: ingress
              target: 11633
              published: 11633
              protocol: tcp
        volumes:
            - type: bind
              source: tracetest.yaml
              target: /app/tracetest.yaml
            - type: bind
              source: ./tracetest-provision.yaml
              target: /app/provision.yaml
    jaeger:
        image: jaegertracing/all-in-one:latest
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "wget", "--spider", "localhost:16686"]
            interval: 1s
            timeout: 3s
            retries: 60
        ports:
            - 16685:16685
            - 16686:16686
networks:
    default:
        name: _default
